import React from 'react';
import { Copy, Check, Code, Terminal } from 'lucide-react';

interface ExportPanelProps {
  path: string;
  color: string;
  active: boolean;
}

/**
 * Design Token Export
 * Generates snippets for React (functional components) and Tailwind CSS.
 */
export const ExportPanel: React.FC<ExportPanelProps> = ({ path, color, active }) => {
  const [copied, setCopied] = React.useState<string | null>(null);

  if (!active) return null;

  const reactSnippet = `
import React from 'react';

/**
 * OrganicBlob Component
 * Generated by Morfic - Organic Design Tool
 */
export const OrganicBlob = ({ size = 400, className = "" }) => (
  <svg 
    viewBox="0 0 400 400" 
    xmlns="http://www.w3.org/2000/svg"
    className={className}
    style={{ width: size, height: size }}
  >
    <path 
      fill="${color}" 
      d="${path}" 
    />
  </svg>
);

export default OrganicBlob;
`.trim();

  const tailwindSnippet = `
<div className="w-64 h-64 bg-[${color}] [mask-image:url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 400"><path d="${path}"/></svg>')]">
  {/* Organic Content */}
</div>
`.trim();

  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopied(id);
    setTimeout(() => setCopied(null), 2000);
  };

  return (
    <div className="w-full max-w-4xl bg-white dark:bg-gray-800 rounded-3xl p-8 shadow-xl border border-gray-100 dark:border-gray-700 mt-8 animate-in fade-in slide-in-from-bottom-4 duration-500 transition-colors">
      <div className="flex items-center gap-3 mb-8">
        <div className="w-10 h-10 rounded-xl bg-accent/10 text-accent flex items-center justify-center">
          <Terminal className="w-5 h-5" />
        </div>
        <h3 className="text-xl font-bold text-gray-800 dark:text-white">Design Tokens</h3>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {/* React Component */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <span className="text-sm font-bold text-gray-500 dark:text-gray-400 flex items-center gap-2 uppercase tracking-wider">
              <Code size={14} /> React Component
            </span>
            <button 
              onClick={() => handleCopy(reactSnippet, 'react')}
              className="text-gray-400 hover:text-accent dark:hover:text-accent transition-colors"
            >
              {copied === 'react' ? <Check size={18} className="text-green-500" /> : <Copy size={18} />}
            </button>
          </div>
          <pre className="bg-gray-50 dark:bg-gray-900/50 p-4 rounded-2xl text-xs font-mono text-gray-600 dark:text-gray-300 overflow-x-auto border border-gray-100 dark:border-gray-700">
            {reactSnippet}
          </pre>
        </div>

        {/* Tailwind CSS */}
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <span className="text-sm font-bold text-gray-500 dark:text-gray-400 flex items-center gap-2 uppercase tracking-wider">
              <Terminal size={14} /> Tailwind CSS Mask
            </span>
            <button 
              onClick={() => handleCopy(tailwindSnippet, 'tailwind')}
              className="text-gray-400 hover:text-accent dark:hover:text-accent transition-colors"
            >
              {copied === 'tailwind' ? <Check size={18} className="text-green-500" /> : <Copy size={18} />}
            </button>
          </div>
          <pre className="bg-gray-50 dark:bg-gray-900/50 p-4 rounded-2xl text-xs font-mono text-gray-600 dark:text-gray-300 overflow-x-auto border border-gray-100 dark:border-gray-700">
            {tailwindSnippet}
          </pre>
        </div>
      </div>
    </div>
  );
};
